// Generated by CoffeeScript 1.11.1
var mousePressed, setup;

setup = function() {
  createCanvas(windowWidth, windowHeight);
  return bg(0.5);
};

mousePressed = function() {
  return text("x=" + mouseX + " y=" + mouseY, mouseX, mouseY);
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUE7O0FBQUEsS0FBQSxHQUFRLFNBQUE7RUFDUCxZQUFBLENBQWEsV0FBYixFQUF5QixZQUF6QjtTQUNBLEVBQUEsQ0FBRyxHQUFIO0FBRk87O0FBSVIsWUFBQSxHQUFlLFNBQUE7U0FDZCxJQUFBLENBQUssSUFBQSxHQUFLLE1BQUwsR0FBWSxLQUFaLEdBQWlCLE1BQXRCLEVBQWdDLE1BQWhDLEVBQXdDLE1BQXhDO0FBRGMiLCJzb3VyY2VzQ29udGVudCI6WyJzZXR1cCA9IC0+XHJcblx0Y3JlYXRlQ2FudmFzIHdpbmRvd1dpZHRoLHdpbmRvd0hlaWdodFxyXG5cdGJnIDAuNVxyXG5cdFx0XHRcdFx0XHJcbm1vdXNlUHJlc3NlZCA9IC0+XHJcblx0dGV4dCBcIng9I3ttb3VzZVh9IHk9I3ttb3VzZVl9XCIsIG1vdXNlWCwgbW91c2VZIl19
//# sourceURL=C:\Lab\2017\000-Mall\coffee\sketch.coffee