// Generated by CoffeeScript 1.11.1
var draw, setup;

setup = function() {
  createCanvas(windowWidth, windowHeight);
  return bg(0.5);
};

draw = function() {
  return text("x=" + mouseX + " y=" + mouseY, mouseX, mouseY);
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6Ii4uIiwic291cmNlcyI6WyJjb2ZmZWVcXHNrZXRjaC5jb2ZmZWUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLElBQUE7O0FBQUEsS0FBQSxHQUFRLFNBQUE7RUFDUCxZQUFBLENBQWEsV0FBYixFQUF5QixZQUF6QjtTQUNBLEVBQUEsQ0FBRyxHQUFIO0FBRk87O0FBSVIsSUFBQSxHQUFPLFNBQUE7U0FDTixJQUFBLENBQUssSUFBQSxHQUFLLE1BQUwsR0FBWSxLQUFaLEdBQWlCLE1BQXRCLEVBQWdDLE1BQWhDLEVBQXdDLE1BQXhDO0FBRE0iLCJzb3VyY2VzQ29udGVudCI6WyJzZXR1cCA9IC0+XHJcblx0Y3JlYXRlQ2FudmFzIHdpbmRvd1dpZHRoLHdpbmRvd0hlaWdodFxyXG5cdGJnIDAuNVxyXG5cdFxyXG5kcmF3ID0gLT5cclxuXHR0ZXh0IFwieD0je21vdXNlWH0geT0je21vdXNlWX1cIiwgbW91c2VYLCBtb3VzZVlcdFx0XHRcdFx0XHJcbiJdfQ==
//# sourceURL=C:\github\000-Mall\coffee\sketch.coffee