// Generated by CoffeeScript 1.11.1
var mousePressed, setup;

setup = function() {
  createCanvas(windowWidth, windowHeight);
  return bg(0.5);
};

mousePressed = function() {
  return text("x=" + mouseX + " y=" + mouseY, mouseX, mouseY);
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsic2tldGNoLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEsSUFBQTs7QUFBQSxLQUFBLEdBQVEsU0FBQTtFQUNQLFlBQUEsQ0FBYSxXQUFiLEVBQXlCLFlBQXpCO1NBQ0EsRUFBQSxDQUFHLEdBQUg7QUFGTzs7QUFJUixZQUFBLEdBQWUsU0FBQTtTQUNkLElBQUEsQ0FBSyxJQUFBLEdBQUssTUFBTCxHQUFZLEtBQVosR0FBaUIsTUFBdEIsRUFBZ0MsTUFBaEMsRUFBd0MsTUFBeEM7QUFEYyIsInNvdXJjZXNDb250ZW50IjpbInNldHVwID0gLT5cclxuXHRjcmVhdGVDYW52YXMgd2luZG93V2lkdGgsd2luZG93SGVpZ2h0XHJcblx0YmcgMC41XHJcblx0XHRcdFx0XHRcclxubW91c2VQcmVzc2VkID0gLT5cclxuXHR0ZXh0IFwieD0je21vdXNlWH0geT0je21vdXNlWX1cIiwgbW91c2VYLCBtb3VzZVkiXX0=
//# sourceURL=C:\github\000-Mall\sketch.coffee